title: "Your Name â€” Technical & Content Writer"
email: your.email@example.com
description: "Technical writer, UX content strategist."

# Use Minimal Mistakes as a remote theme
remote_theme: jekyll-theme-minimal

# Minimal site navigation example
nav:
  - title: "About"
    url: /about/
  - title: "Work"
    url: /work/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/
